--- arch/arm/mach-msm/Makefile
+++ arch/arm/mach-msm/Makefile
@@ -433,6 +433,9 @@
 obj-$(CONFIG_MMI_SOC_INFO) += mmi_soc_info.o
 obj-$(CONFIG_MMI_MSM_PINMUX) += mmi-pinmux.o
 obj-$(CONFIG_PM_DEBUG) += pm_debug.o
+<<<<<<< HEAD
 
 obj-$(CONFIG_LCD_KCAL) += board_kcal.o kcal_ctrl.o
 obj-$(CONFIG_INTELLI_PLUG) += intelli_plug.o
+=======
+>>>>>>> cd382be... intelli_plug: Remove old mach-msm Kconfig/Makefile entries
